### ISSUE TITLE
Procedural probe core description lacks important detail

### ISSUE THREAD

**Issue by byt3c** [KSP-RO/ProgramsIssueTracker#117]
Procedural probe core costs a lot without explaining it also enables deep space capabilities before procedural avionics have this ability.

Instead of generic description it should say - first deep space probe cores :)
![obraz](https://user-images.githubusercontent.com/38114978/231983561-a9cecad5-f577-42bd-9cc6-c3d6d47314a8.png)

**Comment by jeremyneumann** [comment]
This should be opened under [KSP-RO/ROTanks](https://github.com/KSP-RO/ROTanks) to update the description or more ideally [KSP-RO/RP-0](https://github.com/KSP-RO/RP-0) to remove Deep Space Avionics from the ECM as it should have no balance impact if its not unlocked with the part.

**Comment by arrowmaster** [comment]
This should be opened under [KSP-RO/ROTanks](https://github.com/KSP-RO/ROTanks) to update the description or more ideally [KSP-RO/RP-0](https://github.com/KSP-RO/RP-0) to remove Deep Space Avionics from the ECM as it should have no balance impact if its not unlocked with the part.

**Comment by byt3c** [comment]
I need to check if this is exactly the same in Classical RP tech tree experience. Isn't tech tree bit different under rp1 ?

**Comment by arrowmaster** [comment]
Its mostly only different with engines. It looks like it was originally set to need Deep Space Avionics by @siimav in https://github.com/KSP-RO/RP-0/commit/25542437d0cafbc0b42458a0d549dab75db06816. In theory it should work to change it to use avionicsBasic instead of avionicsProbesBasic. Balance wise I don't see why it should require Deep Space instead of Near Space.

Both the part and Deep Space Avionics are supposed to unlock in the same node and the ECMs are displayed in the module list on the side so there is no need to update the description.

**Comment by byt3c** [comment]
So i leave it to you to decide what to do with it- you are obviously more knowledgeable where and how to fix it :)

**Comment by NathanKell** [comment]
Yeah this is a base RP-0 issue.
