### ISSUE TITLE
Remove soft cooldowns

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/ProgramsIssueTracker#15]
At least from the early contracts. We should keep them for repeatable comm/weather/nav etc.

**Comment by lpgagnon** [comment]
without cooldowns, XPSS will typically involve making a bunch of flights back-to-back to climb up the speed ladder, even though the first flight could have hit a higher target right away (perhaps not with the first plane, but probably with the second - who'd build a new plane for a single 50m/s increment?). Might be interesting to turn XPSS into records instead? (if records can be gated behind a program)

**Comment by leudaimon** [comment]
Regarding XPSS, it's even more strange, because Max suggested in the sheet that only the contracts above the required 600 m/s should give any Rep. It would be really boring to climb the ladder, cooldown or no, just to reach the 600m/s without any reward for these 5 flights. On the other side, I think we should incentivize people to upgrade and/or build multiple supersonic planes as they research new tech.

**Comment by Amanthebest4** [comment]
how about a reverse soft cooldown for xpss? so the earlier you complete the contract the better the reward. this incentivizes actively building the fastest plane you can, and making new planes that are slightly faster for the next contract asap.

**Comment by NathanKell** [comment]
If required don't give rep then it is optimal to wait until the J57 unlocks and bang out all of the XPSS requireds at once (since J47 can't do Mach 2). @ppboyle I think this is more argument for requireds giving rep. ;) 
It is immaterial whether there are cooldowns or not, for that point, honestly.

**Comment by NathanKell** [comment]
Believe this is sorted out now.
