### ISSUE TITLE
Sounding payload and bio should be in VPG

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/ProgramsIssueTracker#20]
Bio sample contract doesn't require the sample and the Sounding Payload to return, I think? And it should. Probably same for other "Return Home" contracts.

**Comment by Teykn** [comment]
As far as I can tell, all of the contracts that need something returned are all in VPGs, including the SR Bio, Film, and Adv Bio contracts, so they all should require the payload and science (part) to return safely. Maybe a `disableOnStateChange = false` is needed for the HasResource and PartValidation parameters, since I'm not sure what the default is for those parameters.

**Comment by NathanKell** [comment]
The return-home parameter is outside the VPG but the VPG will go false if anything but alt fails, yes, you're correct. I mostly just saw the return-home being outside the VPG.
