### ISSUE TITLE
Split X-plane program into two parts

### ISSUE THREAD

**Issue by norcalplanner** [KSP-RO/ProgramsIssueTracker#24]
Right now there's one program titled Early X-Plane Research.  This program requires that 13 separate missions be flown, including three which can only be flown with an X-15 cockpit, which is pretty far down the tech tree.  At the very least, the program should be reduced to 10 flights and stop after the third suborbital hop, which is 70 km and can be completed by the upgraded X-1 cockpit.  

For a kinder, gentler, and shorter program, the dividing line between Early X-Planes and the yet-to-be-written Advanced X-Planes program could be at 30 km so it can be completed with a standard X-1 cockpit.

**Comment by NathanKell** [comment]
I strongly disagree with this. The program has a duration of 8 years, which should be enough time to complete all contracts. Further, it is specifically the case that the program requires the player to design multiple craft; this is a good thing, not a bad thing (just as other programs also require multiple craft designs).

Splitting it in this way results in:
(a) it being pretty much a no-brainer to take, because it gives a bunch of rep (and funding) thanks to its records and optionals, for the cost of two tech nodes, maybe 3 (if you can't quite cheese Mach 2 off the first real supersonic node).
(b) it requires precisely two aircraft (or one, if you edit the rocket to the jet).
(c) if you don't take it early, and it is required for the X-15 program, you can bang it out in very short order (see a/b)
(d) the second program would have precisely 3 contracts (with the 70km dividing line).

If you split at 30km then the first three points become even sharper relief.

Having the X-Planes program is about having a meaningful choice early. It forces you to go down a tree branch you otherwise might not. Splitting it takes away meaning from that choice IMO, and takes us much closer to the release version of the early game, where the choice is "do all the things".

**Comment by norcalplanner** [comment]
Could the program at least be retitled to X-Plane Research then?  Having "Early" in the title seems somewhat misleading for something that goes from breaking the sound barrier for the first time all the way up to breaking the Karman line.

**Comment by NathanKell** [comment]
That I do agree with, "Early" is a trap. We can just call it X-Planes I think, since we have no plans for a later X-Planes program.

**Comment by Elouda** [comment]
> I strongly disagree with this. The program has a duration of 8 years, which should be enough time to complete all contracts. Further, it is specifically the case that the program requires the player to design multiple craft; this is a good thing, not a bad thing (just as other programs also require multiple craft designs).

8 years means taking it at the start, your deadline is equivalent with one of the tech nodes _required_ for it at the moment, which is very counterintuitive, and unless you push a few years ahead of time research on it means it will not be complete on time.

On the other hand, taking it anytime _but_ right at the start means
a) not possible to do historical X-1/X-2 etc
b) program becomes worthless as its annual funding is eclipsed very quickly by others, and having it locked in for 8 years leaves your overall funding reduced

The other option to do it is to take it once you have 3 program slots, but its still very non-optimal, because at this point
a) this is only really going to happen ~1960 or later
b) thus you will probably miss all the deadlines for historical equivalents
c) you are still cheating yourself out of cash compared to just taking more lunar/inner planets/crewed programs, and at this point the rep is a drop in the bucket

I would strongly urge to consider splitting it into 2, along the lines suggested above as follows;
a) Early X-Planes - 5/6 years, reduce funding to 40k/year from current 60k/year, requires 6 supersonic and 5 suborbital flights - suborbital flights start at 30, and go to 70. Reduce rep rewards for the earlier cases of supersonic and suborbital, and add the cooldown back to suborbital (90 days maybe?)
b) Advanced/Suborbital X-Planes - 5/6 years, funding of ~100k/year (contrast with early lunar at 200k/year), requires a further 7 suborbital flights (80 thru 140), plus 2 'true' suborbital flights over 140km, and a further 3 supersonic flights (essentially requiring the X-15 node and the plane node above it).

Alternatively, make planes entirely independent of the program system, because as it stands doing the program is massively sub-optimal and a literal 'ball and chain' due to locking in a program for 8 years that offers starting tier funding, moderate rep gain (much of which you can get without the program via records), and _requires_ 1959 tech to complete.

**Comment by Amanthebest4** [comment]
I disagree about the cooldowns. with soft cooldowns the way they are and the rep cap being a thing, it is always going to be a no-brainer to progress through the program as fast as possible, because the early completion rep helps with the rep you skipped (to a degree) and having that program, which is early level budget, out of the way is top priority IMO.

about the whole splitting thing, I see both sides. if you split them up, going into xpss is not really a tradeoff, but locking down a precious program slot with xpss for 8 years is a bit much. my proposition: make difficult contracts to xpss (the ones which go up in steps of 15km, or up in speed by 150m/s basically three times the step as normal)(1.5x normal rep). and give us a choice to do the full 13 standard set or replace them with 5 difficult contracts and end the program early. this will need the player to make a significant sacrifice by rushing tech nodes, losing about 50% rep and funding by ending early.

i like the whole thing about having to make a tradeoff, so I propose to add further to it for choosing your own priorities.

**Comment by lpgagnon** [comment]
Meanwhile, I concluded it made sense to start the program after completing a SR program (~ early 1953), at which point the 8 years seemed perfectly adequate.

It seems like a good thing that the program actually gives a reason to commit to go all the way to x-15.

I do however feel making the program available from the start, with the 8-year undeadline, is a bit of a trap. So... just bump it up?

**Comment by leudaimon** [comment]
I actually had a similar idea. It's hard to justify blocking it behind some uncrewed contract, but I think it would help people avoiding to get it at start, as it's a proper trap. 

However, the fact it's a trap to do it at start makes the early contracts (namely break sound barrier, first few tiers of SSPX) a bit out of place. It probably still makes sense to keep them together in this program. An inexperienced player would start flying planes at all when they accept this contract, and if people want to build a plane before the program to get supersonic science and a couple records, it shouldn't brake much balance.

**Comment by lpgagnon** [comment]
to clarify: I meant bump up the deadline, not the availability time

**Comment by marsh1832** [comment]
I agree about removing X-Planes from the program system. I think the folly here is trying to balance planes within a program system very largely about going into space. Planes are already divisive as it is, and why place a trap program in to fool new players? I think they should be optional (if optimal) contracts. In fact, there's no world where they aren't optimal (in contract form) unless you're going "no planes." It seems really odd to pass on the program until later, and then go back to making a supersonic plane from the early 50's.

To me it makes the most sense to keep X-Plane contracts separate from programs, and leave it up to the player if they want planes or no planes, and balance the contracts appropriately. When it comes to speed runs people can specify if they are planes or no planes when comparing dates. Or taking from other speed running communities, certain settings/game versions/consoles are simply faster/more optimal compared to others, and that's just how it is. If you want to be the best, then you have to be optimal. If you don't care, then planes or no planes as you prefer.

**Comment by Elouda** [comment]
Or if removing them from the system, have the 'no planes' option just distribute the rep from their contracts into the early rocket contracts up to FO or something like is the case now with money boost.

**Comment by Amanthebest4** [comment]
@Elouda it seems like that would be unnecessary. afaict, they intend for you to do the low space film return, etc. program to make  up for it. also, I think if you just distribute the points into other stuff you would've done anyways with planes, it makes the choice of not doing planes "better". you'd have to do less for the same rewards. that's very screwy, because you can also take another program, making it as if you're taking 3

**Comment by Elouda** [comment]
To be clear I didn't mean all of it, I just meant something similar to the current no-planes option where you get some bonuses to the other contracts to make up for it.

**Comment by NathanKell** [comment]
Early game has been reworked.
