### ISSUE TITLE
Building construction does not complete when running a simulation in the future.

### ISSUE THREAD

**Issue by ajvaughan** [KSP-RO/ProgramsIssueTracker#31]
Building construction does not complete when running a simulation in the future.

I tried to do a sim for a moon impactor + orbiter roughly 300 days in the future when manoeuvre nodes should have been available.
However construction hadn't advanced.

**Comment by NathanKell** [comment]
Yeah, that's not going to work. And it's quite the rabbit hole to get to work, since the way things build they build per tick, there isn't some analytical system like how orbits are on rails. (Because it's not even as simple as "do one big timestep", because say you sim 300 days in the future and there's an LC that's only taking 5 days and then the MC takes another 200 days...well, clearly you expect both to be done).

Unless that's something @siimav wants to think about (from the simulation side) I'm totally punting on this.

**Comment by ajvaughan** [comment]
Fair enough.

**Comment by Teykn** [comment]
Maybe allow any level of TS/MC to be chosen when simulating? Hopefully that isn't a nightmare to code since I have no clue

**Comment by NathanKell** [comment]
Did a slim version of this where buildings that are estimated to complete before the sim starts will have their progress set to 100% (and should complete during the first frames of the sim). No other progress on KCT projects will be done, nor efficiencies changed (which means the time the buildings need to complete is an overestimate). Anyway, hope that's enough, doing more is too much of a rabbit hole.
