### ISSUE TITLE
Free Airlaunch!

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProgramsIssueTracker#32]
- Load a save that has a plane ready to launch, NOT prepped for airlaunch
- Prep it for airlaunch, airlaunch it
- Once on the runway, hit Esc and re-load the original save
- Now that plane is back to not-prepped, hit Launch
-> get the normal select-crew UI, no airlaunch UI (good)
-> but once on the runway, airlaunch sequence begins (bad)

Pretty good chance this exists in rp-1 release.

caveat: first time I encountered this "airlaunched without asking for it" bug today, I'm fairly sure I didn't do that airlaunch-and-reload dance; only found these steps while trying to reproduce. So there may be a more subtle, accidental way to trigger it. Possibly by actually going through with the airlaunch, recovering, then launching again? I definitely had done an actual airlaunched flight previously.

**Comment by NathanKell** [comment]
Yup, this is definitely an old issue. Gonna punt until I refactor KCT to not be static, because the very staticness that lets airlaunch work (set in the space center scene, the params stick around on load to flight) *also* means they stick around on loading a different save since scene transitions are loading saves underneath...
