### ISSUE TITLE
Can't leave applicants-from-science linear

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/ProgramsIssueTracker#55]
Gives too many applicants. But the old formula did too little...

**Comment by ajvaughan** [comment]
Maybe 5, 10, 20, 40, 80 etc ?

**Comment by NathanKell** [comment]
Before it was (x^.75) and that wasn't enough, we need something *more* generous than that, not less.

**Comment by dgeastman** [comment]
I've certainly been noticing in my current play-through that in the early years (the first two suborbital contracts), I'm getting applicants at a rate far beyond what I can actually afford to hire. I've often been leaving 20+ applicants just sitting there because I wasn't ready to pay their salaries.

**Comment by NathanKell** [comment]
Trying the 0.92 power.
